### ISSUE TITLE
Console auto-popout isn't working

### ISSUE THREAD

**Issue by LazoYoung** [ME1312/SubServers-2#36] opened 2019-01-23 02:36 UTC
### Platform Information
Windows 10 [x64],
Java 1.8.0_191 [x64],
BungeeCord git:BungeeCord-Bootstrap:1.13-SNAPSHOT:9a2acc8:1390,
SubServers.Bungee v2.13.2c (19w04b)

### What Happened
**/autopopout server < subserver >** doesn't pop-out a new console after booting.  

### How It Happened
1. Install Subservers
2. Put Subservers-console in proxy's plugins folder
3. Install a subserver A
4. Start up proxy and type **/autopopout server A**
5. Restart proxy. Console for A is never created so I have to manually open it by /popout server A

### Additional Information
~

**Comment by ME1312** [comment] 2019-01-23 03:32
I'm not seeing this issue on my end. Is there something more specific on your end that might be going on to have this occur?

Attached is SubServers.Console's auto-popout functionality behaving properly, just so there's no confusion on what is supposed to be happening (don't mind the debug messages):
> **First run:** https://gyazo.com/fcacc9f807d83b2a432b10270461ee0c
> **After a restart:** https://gyazo.com/aaace8ab26e663d9107bab77094c1527

**Comment by LazoYoung** [comment] 2019-01-23 04:21
[log.txt](https://github.com/ME1312/SubServers-2/files/2785651/log.txt)
Here's the entire log. Please see my comments on top of the file.

EDIT: I forgot to mention that I set **run-on-launch: true** for my subserver.

**Comment by ME1312** [comment] 2019-01-23 17:29
This issue was caused by the server processes launching before SubServers.Console was loaded. Fixed as of the latest snapshot

**Closed as completed by ME1312** 2019-01-23 17:29 UTC
Labels: Bug, Resolved
